### ISSUE TITLE
Using name of other app

### ISSUE THREAD

**Issue by martin-key** [david340804/NanoStats#4]
Hello David! 

I am the creator of Nanostats app in the iOS AppStore. As the name of your app is making confusion with some of the users I want to ask is it is possible to change it? Thanks! 
Good work with react native BTW!

**Comment by martin-key** [comment]
Hello David!
It has been 3 weeks and I see no change in the name of the app. If it is not changed until the end of the next week I will have to send Apple signal for that and they may block your account (which sucks because you have paid $100 for it). Please respond.

**Comment by davidgamero** [comment]
@StarbuckBG I see that you have an app with the same name that was registered before mine. I'll change the name to "Nanopool Stats" to avoid the confusion

**Comment by martin-key** [comment]
Thanks David!

Highly appreciated. Nice app BTW. 


Best regards,
Martin Kuvandzhiev

mobile: +359 887 458 634
us: +1 301 886 0544
email: martinkuvandzhiev@gmail.com
telegram: @MartinKey
twitter: @mkuvandzhiev
